Add developer mode option to show RTC connection statistics
element-hq/element-call pull request #2904
Opened 2024-12-16 17:05 UTC by hughns

New option in developer settings:

<img width="639" alt="image" src="https://github.com/user-attachments/assets/eab5057b-11e2-43d0-9f81-6b3ec29b5ddf" />

Which overlays some basic info on audio and video when available:

<img width="904" alt="image" src="https://github.com/user-attachments/assets/8495ecb3-5561-464b-8787-5bb707a52d39" />

And you can hover to get the full `RTCInboundRtpStreamStats | RTCOutboundRtpStreamStats` data:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/35897a29-2dc4-48d8-84a1-bf1e776d9f03" />

2024-12-16 18:08 UTC, toger5 commented
This introduces some odd horizontal scrolling on Firefox:
![image](https://github.com/user-attachments/assets/04b6c48a-7347-49a3-8bca-c0a5546e0110)

2024-12-16 18:13 UTC, toger5 commented
Could be the tooltip provider?

2024-12-17 08:12 UTC, hughns commented
> This introduces some odd horizontal scrolling on Firefox:

Good spot. It's the same on Chrome too.

2024-12-18 17:30 UTC, hughns commented
I've moved the detailed data into a modal and I think it's probably good enough for now.

2024-12-19 10:43 UTC, toger5 requested changes
It is hard to tell how much time and effort we want to put into this.
There are a couple of issues:
your own stream does not show reasonable data:
![image](https://github.com/user-attachments/assets/78f0ee81-4639-49b1-b477-4210d2f5434f)

The styling is hard to read, the buttons are super small.
But I suspect this is just debug information and should not be used by users who want EC to be pretty.
I will give it a quick try to change the css to be a bit more fitting and you can check if you like it.

2024-12-19 11:33 UTC, toger5 commented
Here are the proposed changes: https://github.com/element-hq/element-call/pull/2916

2025-01-06 09:45 UTC, hughns commented
> It is hard to tell how much time and effort we want to put into this.

Answer: Not a lot of effort.

This was intended to surface easily accessible information.

> your own stream does not show reasonable data: ![image](https://private-user-images.githubusercontent.com/16718859/397337806-78f0ee81-4639-49b1-b477-4210d2f5434f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTY4ODMsIm5iZiI6MTczNjE1NjU4MywicGF0aCI6Ii8xNjcxODg1OS8zOTczMzc4MDYtNzhmMGVlODEtNDYzOS00OWIxLWI0NzctNDIxMGQyZjU0MzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA5NDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MDVkODkxMDIzOTU3MjE5Y2VjMjc5ZGIyMjI5NmVlYjg3MzUxMDExNmQ3MTAxNjQ5ZmUyMDc4MTVjNzNhMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UfjR3-5xZO9qcvJPzhheDKKxVB0ahvjPaU9IyrHuxI0)

As this isn't a full feature this is fine for now. If/when we want own stats for debugging then we can wire more of them in.

> The styling is hard to read, the buttons are super small. But I suspect this is just debug information and should not be used by users who want EC to be pretty. I will give it a quick try to change the css to be a bit more fitting and you can check if you like it.

I've merged your proposal 👍

2025-01-06 09:47 UTC, merged