Use .ts files for vite config for type safety
element-hq/element-call pull request #2912
Opened 2024-12-18 13:32 UTC by hughns

2024-12-19 10:16 UTC, toger5 requested changes

2024-12-19 10:16 UTC, toger5 commented on tsconfig.json
> +    "skipLibCheck": true,
This seems to be a step back in how strict we do our typing.
Are we sure we want this? Is there no way to fix the reason we add this with yarns resolutions?
Can it get a comment why we need this now?

2025-01-06 10:52 UTC, hughns commented on tsconfig.json
> +    "skipLibCheck": true,
I concur that this is a backwards step. Unfortunately it's not just the case of some resolutions.

The main culprit appears to be @codecov/vite-plugin.

I will make this draft and lift the one material change over to a simpler PR.

2025-08-04 16:52 UTC, toger5 commented
replaced by: https://github.com/element-hq/element-call/pull/3443

2025-08-04 16:52 UTC, closed without merging